import React from "react";
import Header from "../../components/navbar";
import { NextPage } from "next";
import Head from "next/head";


const CreateTransactions : NextPage = () => {

    return (
        <>
            <Head>
                <title>Transactions | NewCombin Challenge</title>
                <meta name="description" content="Generated by create-t3-app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Header activePage="Transactions" />
            
        </>
    )
}

export default CreateTransactions;