import React from "react";
import Header from "../../components/navbar";
import Footer from "../../components/footer";
import { NextPage } from "next";
import Head from "next/head";

const Transactions: NextPage = () => {
    return(
        <>
            <Head>
                <title>Transactions | NewCombin Challenge</title>
                <meta name="description" content="Generated by create-t3-app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Header activePage="Transactions"/>
            <main className="container mx-auto flex flex-col items-center justify-center min-h-screen p-4">
                <h1>Transactions</h1>
            </main>

            <Footer />
        </>
    )
}

export default Transactions;