import React from "react";
import Header from "../components/navbar";
import Head from "next/head";

export default function Custom404(){
    return(
        <>
            <Head>
                <title>404 | NewCombin Challenge</title>
                <meta name="description" content="Generated by create-t3-app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Header activePage="404"/>
            <main className="container mx-auto flex flex-col items-center justify-center min-h-screen p-4">
                <h1>404 | Page not found</h1>
            </main>
            
        </>
    )
}