import React from "react";
import Header from "../../components/navbar";
import { NextPage } from "next";
import Head from "next/head";
import {trpc} from "../../utils/trpc";
import Filters from "../../components/filters";

const Payables: NextPage = () => {
    const payables = trpc.useQuery(["payables.getAll"]);

    

    if(!payables.data) {
        return (
            <>
            <Head>
                <title>Payables | NewCombin Challenge</title>
                <meta name="description" content="Generated by create-t3-app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Header activePage="Payables"/>

            <Filters typeFilter="payables" />
            
            <div className="flex justify-center items-center h-screen">
                <div className="w-full max-w-md">
                        
                    <div className="bg-white shadow-md rounded px-8 pt-6 pb-8 mb-4">
                        <div className="mb-4">
                            <h1 className="text-2xl font-bold text-center">
                                Loading...
                            </h1>
                        </div>
                    </div>
                </div>
            </div>
            </>
        )
    }
    return(
        <>
            <Head>
                <title>Payables | NewCombin Challenge</title>
                <meta name="description" content="Generated by create-t3-app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Header activePage="Payables"/>
            <main className="container mx-auto flex flex-col items-center justify-center min-h-screen p-4">
                <h1>Payables</h1>
                <ul>
                    {payables.data.map((payable) => (
                        <li key={payable.id}>
                            {payable.id} - {payable.amount}
                        </li>
                    ))}
                </ul>
            </main>

            
        </>
    )
}

export default Payables;

