import React from "react";
import Header from "../../components/navbar";
import { NextPage } from "next";
import Head from "next/head";
import { trpc } from "../../utils/trpc";
import Filters from "../../components/filters";

const Payables: NextPage = () => {

    const payables = trpc.useQuery(["payables.getAll"]);

    if (!payables.data?.length) {
        return (
            <>
                <Head>
                    <title>Payables | NewCombin Challenge</title>
                    <meta name="description" content="Generated by create-t3-app" />
                    <link rel="icon" href="/favicon.ico" />
                </Head>
                <Header activePage="Payables" />

                <Filters typeFilter="Payables" typeBtn="createPayable" />

                <div className="flex justify-center items-center h-screen">
                    <div className="w-full max-w-md">

                        <div className="bg-white shadow-md rounded px-8 pt-6 pb-8 mb-4">
                            <div className="mb-4">
                                <h1 className="text-2xl font-bold text-center">
                                    Loading...
                                </h1>
                            </div>
                        </div>
                    </div>
                </div>
            </>
        )
    }



    return (
        <>
            <Head>
                <title>Payables | NewCombin Challenge</title>
                <meta name="description" content="Generated by create-t3-app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Header activePage="Payables" />
            <Filters typeFilter="Payables" typeBtn="createPayable" />
            <main className="container mx-auto flex flex-col justify-center p-4">
                

                <div className="flex flex-col">
                        <div className="overflow-x-auto sm:-mx-6 lg:-mx-8">
                            <div className="py-2 inline-block min-w-full sm:px-6 lg:px-8">
                              <div className="overflow-hidden">
                                <table className="min-w-full divide-y divide-gray-200">
                                    <thead>
                                        <tr>
                                            <th className="px-4 py-2">Service</th>
                                            <th className="px-4 py-2">Barcode</th>
                                            <th className="px-4 py-2">Amount</th>
                                            <th className="px-4 py-2">Status</th>
                                            <th className="px-4 py-2">Expiration Date</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        {payables.data.map((payable) => (
                                            <tr key={payable.id}>
                                                <td className="border px-4 py-2">{payable.typeService}</td>
                                                <td className="border px-4 py-2">{payable.barcode}</td>
                                                <td className="border px-4 py-2">{payable.amount}</td>
                                                <td className="border px-4 py-2">{payable.status}</td>
                                                <td className="border px-4 py-2">{payable.expirationDate.toISOString()}</td>
                                            </tr>
                                        ))}
                                    </tbody>
                                </table>
                              </div>
                            </div>
                        </div>
                </div>

            </main>


        </>
    )
}

export default Payables;

