import React from "react";
import Header from "../../components/navbar";
import { NextPage } from "next";
import Head from "next/head";
import { trpc } from "../../utils/trpc";
import Filters from "../../components/filters";

const Payables: NextPage = () => {

    return (
        <>
            <Head>
                <title>Payables | NewCombin Challenge</title>
                <meta name="description" content="Generated by create-t3-app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Header activePage="Payables" />
            <Filters typeBtn="createPayable" />
        </>
    )
}

export default Payables;

